// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Liv.Lck.Core
{
    internal static partial class LckCoreTelemetryNative
    {
        const string __DllName = "lck_core";





        [DllImport(__DllName, EntryPoint = "send_telemetry_event_without_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TelemetryReturnCode send_telemetry_event_without_context(LckTelemetryEventType telemetry_event_type);

        [DllImport(__DllName, EntryPoint = "send_telemetry_event_with_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TelemetryReturnCode send_telemetry_event_with_context(LckTelemetryEventType telemetry_event_type, IntPtr serialized_context_data_ptr, System.UIntPtr len, SerializationType serialization_type);

        [DllImport(__DllName, EntryPoint = "clear_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TelemetryReturnCode clear_context(LckTelemetryContextType context_type);

        [DllImport(__DllName, EntryPoint = "set_telemetry_context_from_serialized_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TelemetryReturnCode set_telemetry_context_from_serialized_data(LckTelemetryContextType context_type, IntPtr serialized_context_data_ptr, System.UIntPtr len, SerializationType serialization_type);


    }


    internal enum TelemetryReturnCode : uint
    {
        Ok = 0,
        Panic = 1,
        FailedToClearContext = 2,
        FailedToSetContext = 3,
        FailedToRetrieveState = 4,
        FailedToDeserializeContext = 5,
        InvalidArgument = 6,
    }

    /// <summary>
    ///  Types of telemetry context.
    /// </summary>
    internal enum LckTelemetryContextType : uint
    {
        RecordingContext = 0,
        StreamingContext = 1,
    }


}
