// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Liv.Lck.Core.FFI
{
    internal static partial class LckCoreNative
    {
        const string __DllName = "lck_core";



        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void start_login_attempt_callback_delegate(ReturnCode return_code, IntPtr login_code);



        [DllImport(__DllName, EntryPoint = "set_max_log_level", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_max_log_level(LevelFilter level);

        /// <summary>
        ///  # Safety
        ///  This function is because it expects a raw pointer to the JNI context jobject.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "initialize_android", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode initialize_android(IntPtr context);

        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences an incoming pointer to a C string.
        ///  tracking_id must be a valid null-terminated C string.
        ///  game_info must be a valid GameInfo struct.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "initialize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode initialize(IntPtr tracking_id, GameInfo game_info, LckInfo lck_info);

        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences an incoming pointer to an i32.
        ///  complete is set to 1 if the login is complete, 0 otherwise.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "check_login_attempt_completed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode check_login_attempt_completed(IntPtr complete);

        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences an incoming pointer to a u32.
        ///  remaining is set to the remaining backoff time in seconds.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "get_remaining_backoff_time_seconds", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode get_remaining_backoff_time_seconds(IntPtr remaining);

        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences an incoming pointer to an i32.
        ///  subcribed is set to 1 if the user is subscribed, 0 otherwise.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "is_user_subscribed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode is_user_subscribed(IntPtr subscribed);

        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences an incoming pointer to an i32.
        ///  configured is set to 1 if the user has configured streaming, 0 otherwise.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "has_user_configured_streaming", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode has_user_configured_streaming(IntPtr configured);

        /// <summary>
        ///  # Safety
        ///  This function is because it takes a raw function pointer as a callback.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "start_login_attempt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode start_login_attempt(start_login_attempt_callback_delegate callback);

        [DllImport(__DllName, EntryPoint = "dispose", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ReturnCode dispose();

        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences an incoming pointer to a C string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "log", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void log(LogType level, IntPtr message, IntPtr member_name, IntPtr file_path, int line_number);


    }


    internal enum ReturnCode : uint
    {
        Ok = 0,
        Error = 1,
        Panic = 2,
        InvalidArgument = 3,
        BackendUnavailable = 4,
        Uninitialized = 5,
        BackendDataParsingError = 6,
        BackendClientError = 7,
        UserNotLoggedIn = 8,
        NullPointer = 9,
        LoginAttemptExpired = 10,
        Fatal = 11,
        RateLimiterBackoff = 12,
        InvalidTrackingId = 13,
    }


}
