// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Liv.Lck.Core
{
    internal static partial class LckCoreCosmeticsNative
    {
        const string __DllName = "lck_core";



        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void announce_player_presence_for_session_on_presence_expiry_received_delegate(ulong time_until_expiration_seconds);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void get_local_user_cosmetics_on_cosmetic_available_delegate(IntPtr serialized_cosmetic_data_ptr, System.UIntPtr serialized_data_length, SerializationType serialization_type);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void get_user_cosmetics_for_session_on_cosmetic_available_delegate(IntPtr serialized_cosmetic_data_ptr, System.UIntPtr serialized_data_length, SerializationType serialization_type);



        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences raw pointers from FFI.
        ///  - `player_ids` must be a non-null pointer to an array of `player_ids_len` pointers to valid,
        ///    null-terminated C strings.
        ///  - `session_id` must be a valid, null-terminated C string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "get_user_cosmetics_for_session", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CosmeticsReturnCode get_user_cosmetics_for_session(IntPtr player_ids_array_ptr, System.UIntPtr player_ids_len, IntPtr session_id, get_user_cosmetics_for_session_on_cosmetic_available_delegate on_cosmetic_available);

        [DllImport(__DllName, EntryPoint = "get_local_user_cosmetics", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CosmeticsReturnCode get_local_user_cosmetics(get_local_user_cosmetics_on_cosmetic_available_delegate on_cosmetic_available);

        /// <summary>
        ///  # Safety
        ///  This function is because it dereferences raw pointers from FFI.
        ///  - `player_id` and `session_id` must be non-null, null-terminated C strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "announce_player_presence_for_session", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CosmeticsReturnCode announce_player_presence_for_session(IntPtr player_id, IntPtr session_id, announce_player_presence_for_session_on_presence_expiry_received_delegate on_presence_expiry_received);


    }


    internal enum CosmeticsReturnCode : uint
    {
        Ok = 0,
        Panic = 1,
        FailedToRetrieveState = 2,
        InvalidArgument = 3,
        BackendError = 4,
        FailedToCacheCosmetics = 5,
        FailedToNotifyOnCosmeticAvailable = 6,
        MutexLockError = 7,
        Unauthorized = 8,
    }


}
