// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Liv.Lck.Core
{
    


    /// <summary>
    ///  LCK telemetry event types.
    /// </summary>
    public enum LckTelemetryEventType : uint
    {
        GameInitialized,
        RecordingStarted,
        StreamingStarted,
        ServiceCreated,
        ServiceDisposed,
        CameraEnabled,
        CameraDisabled,
        RecordingStopped,
        StreamingStopped,
        StreamingError,
        PhotoCaptured,
        RecorderError,
        PhotoCaptureError,
        SdkError,
        Performance,
    }


}
