// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Liv.Lck.Core
{
    


    /// <summary>
    ///  Supported types of data serialization.
    /// </summary>
    public enum SerializationType : uint
    {
        MsgPack,
        JsonUTF8,
    }


}
